export const todoList = [
    {
        id: 1,
        title: 'delectus aut autem',
        description: 'id labore ex et quam laborum',
        date: new Date('3.08.2000').toDateString(),
        isShared: true,
    },
    {
        id: 2,
        title: 'quis ut nam facilis et officia qui',
        description: 'quo vero reiciendis velit similique earum',
        date: new Date('4.09.2010').toDateString(),
        isShared: true,
    },
    {
        id: 3,
        title: 'fugiat veniam minus',
        description: 'odio adipisci rerum aut animi',
        date: new Date('7.07.2008').toDateString(),
        isShared: true,
    },
    {
        id: 4,
        title: 'et porro tempora',
        description: 'alias odio sit',
        date: new Date('3.08.2025').toDateString(),
        isShared: true,
    },
    {
        id: 5,
        title: 'laboriosam mollitia et enim quasi',
        description: 'vero eaque aliquid doloribus et culpa',
        date: new Date('3.03.2012').toDateString(),
        isShared: true,
    },
    {
        id: 6,
        title: 'qui ullam ratione quibusdam ',
        description: 'et fugit eligendi deleniti quidem qui sint nihil autem',
        date: new Date('10.08.2007').toDateString(),
        isShared: true,
    },
    {
        id: 7,
        title: 'illo expedita consequatur quia in',
        description: 'repellat consequatur praesentium vel minus molestias voluptatum',
        date: new Date('3.12.2008').toDateString(),
        isShared: true,
    },
    {
        id: 8,
        title: 'quo adipisci enim quam ut ab',
        description: 'provident id voluptas',
        date: new Date('2.02.2019').toDateString(),
        isShared: true,
    },
    {
        id: 9,
        title: 'React router 1',
        description: 'buy fish',
        date: new Date('2.02.2019').toDateString(),
        isShared: false,
    },
    {
        id: 10,
        title: 'React router 2',
        description: 'pbuy meet',
        date: new Date('2.02.2019').toDateString(),
        isShared: false,
    },
    {
        id: 11,
        title: 'React router 3',
        description: 'buy milk',
        date: new Date('2.02.2019').toDateString(),
        isShared: false,
    },
];

export const serverPath = 'https://powerful-bastion-72531.herokuapp.com';
